name: pc
adopt-info: pc
type: gadget
base: core22
summary: Classic PC gadget for Apple Silicon arm64 devices
description: |
    This gadget enables booting Apple Silicon arm64 with classic Ubuntu
confinement: strict
grade: stable

parts:
  pc:
    plugin: nil
    override-pull: |
      craftctl set version="$(snap info pc | sed -n 's|^  22/edge: *\(22-[0-9.]*\) *202.-.*|\1|p')"
    stage-snaps:
      - pc/22/edge
    stage:
      - -pc-boot.img
  cmdline:
    plugin: dump
    source: dump
